version: 2
jobs:
  build:
    docker:
      - image: circleci/php:latest
      - image: circleci/mysql:8.0

    environment:
      - DB_CONNECTION: mysql_testing
    working_directory: ~/ci-demo
    steps:
      - checkout
      - run: ls
      - run:
          name: Update apt-get
          command: sudo apt-get update
      - run:
          name: Docker php extensions install
          command: sudo docker-php-ext-install pdo_mysql
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "backend/composer.json" }}
            - v1-dependencies-
      - run:
          name: Install PHP libraries
          working_directory: backend
          command: composer install -n --prefer-dist
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "backend/composer.json" }}
      - run:
          name: Run PHPUnit
          working_directory: backend
          command: vendor/bin/phpunit